### ISSUE TITLE
Regular Exception since update to Luna 4.4.1 JEE packaging

### ISSUE THREAD

**Issue by jabby** [angelozerr/eclipse-wtp-webresources#34]
I updated the Eclipse JEE Package this morning. Since I have regular exception in the console log. I thought that it was an Eclipse Exception but it's link to this plugin. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=457537

_Content of my eclipse bug :
Since the update I performed this morning, I have some exceptions in the Error console when I edit some html file or when I move the editor to split my screen in 2 distinct editors._

``` java
java.lang.NullPointerException
	at org.eclipse.wst.html.webresources.core.utils.DOMHelper.getAttrByOffset(DOMHelper.java:316)
	at org.eclipse.wst.html.webresources.core.utils.DOMHelper.getAttrByOffset(DOMHelper.java:308)
	at org.eclipse.wst.html.webresources.core.validation.WebResourcesValidator.validateCSS(WebResourcesValidator.java:408)
	at org.eclipse.wst.html.webresources.core.validation.WebResourcesValidator.validate(WebResourcesValidator.java:385)
	at org.eclipse.wst.html.webresources.core.validation.WebResourcesValidator.validateRegions(WebResourcesValidator.java:360)
	at org.eclipse.wst.html.webresources.ui.validation.WebResourcesSourceValidator.validate(WebResourcesSourceValidator.java:88)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:381)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:259)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)
```

**Comment by angelozerr** [comment]
@jabby could you host in your github, your html which causes problem. Thanks.
