### ISSUE TITLE
Closed project is causing too many stacktraces 

### ISSUE THREAD

**Issue by mniewrzal** [angelozerr/eclipse-wtp-webresources#35]
When project is closed log file is polluted with the same stacktrace. I'm not sure when this happens because this example is from our customer log (10x1mb log files just with this exception during same day). If you need more details, let me know. 

!ENTRY org.eclipse.a.wst.html.webresources.core 4 0 2015-01-05 10:30:58.305
!MESSAGE Error while updating web resources project configuration
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/GeschenkeDe' is not open.
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:150)
	at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:221)
	at org.eclipse.core.internal.resources.Resource.getSessionProperty(Resource.java:1274)
	at org.eclipse.wst.html.webresources.internal.core.WebResourcesProjectConfiguration.getConfiguration(WebResourcesProjectConfiguration.java:53)
	at org.eclipse.wst.html.webresources.internal.core.WebResourcesProjectConfiguration.getOrCreateConfiguration(WebResourcesProjectConfiguration.java:58)
	at org.eclipse.wst.html.webresources.internal.core.search.WebResourcesIndexManager.performAction(WebResourcesIndexManager.java:74)
	at org.eclipse.wst.sse.core.indexing.AbstractIndexManager$1.run(AbstractIndexManager.java:1528)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.wst.sse.core.indexing.AbstractIndexManager$ResourceEventProcessingJob.run(AbstractIndexManager.java:1526)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by angelozerr** [comment]
I think I had fixed this problem https://github.com/angelozerr/eclipse-wtp-webresources/commit/e984a3861545b8b8deb507d3d82fb04f62887bcf 

Which version do you use?

**Comment by mniewrzal** [comment]
Yes you are right, it looks that log was generated with older version (middle of November). Thanks:)
